# permissions for end users to view plays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: play-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple
    app.kubernetes.io/part-of: simple
    app.kubernetes.io/managed-by: kustomize
  name: play-viewer-role
rules:
- apiGroups:
  - kubebuilder-demo.github.com
  resources:
  - plays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubebuilder-demo.github.com
  resources:
  - plays/status
  verbs:
  - get
