---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubebuilder-demo.github.com
  resources:
  - simples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebuilder-demo.github.com
  resources:
  - simples/finalizers
  verbs:
  - update
- apiGroups:
  - kubebuilder-demo.github.com
  resources:
  - simples/status
  verbs:
  - get
  - patch
  - update
